// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNNbaSO0J1px6MLV3QHvupAMEVDlN7v_8',
    appId: '1:14084816707:web:29e07c797a2bf50c89b9f6',
    messagingSenderId: '14084816707',
    projectId: 'myschool-48ec8',
    authDomain: 'myschool-48ec8.firebaseapp.com',
    storageBucket: 'myschool-48ec8.appspot.com',
    measurementId: 'G-3K8815V5ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHhScd5HjQgcprRlDm6sIkNm9peqdoItY',
    appId: '1:14084816707:android:b32a4eeee774f3bd89b9f6',
    messagingSenderId: '14084816707',
    projectId: 'myschool-48ec8',
    storageBucket: 'myschool-48ec8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnKbai87SBTIEyJBWAdQb9aeJmpzmf_vA',
    appId: '1:14084816707:ios:13ef72a3b38735c389b9f6',
    messagingSenderId: '14084816707',
    projectId: 'myschool-48ec8',
    storageBucket: 'myschool-48ec8.appspot.com',
    iosClientId: '14084816707-mqlulc66ukg4q1drpkgdmppgn39h6g8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnKbai87SBTIEyJBWAdQb9aeJmpzmf_vA',
    appId: '1:14084816707:ios:13ef72a3b38735c389b9f6',
    messagingSenderId: '14084816707',
    projectId: 'myschool-48ec8',
    storageBucket: 'myschool-48ec8.appspot.com',
    iosClientId: '14084816707-mqlulc66ukg4q1drpkgdmppgn39h6g8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myschool',
  );
}
